package com.happypuppy.pet.common

enum class AddressType {
    SEOUL, INCHEON, DAEJEON, DAEGU, GWANGJU, BUSAN, ULSAN, SEJONG, GYEONGGI, GANGWON, CHUNGBUK, CHUNGNAM, GYEONGBUK, GYEONGNAM, JEONBUK, JEONNAM, JEJU
}